#!/usr/bin/env python3
"""Sync the CLI reference in the docs with erdify's actual ``--help`` output.

Single source of truth: the argparse parser in ``erdify.cli.build_parser``. This
script renders its help text and writes it into ``docs/usage/cli.md`` between the
``cli-help`` markers, so the published reference can never drift from the CLI.

Usage::

    python scripts/gen_cli_docs.py            # rewrite the block in place
    python scripts/gen_cli_docs.py --check    # exit non-zero if the block is stale

The pre-commit hook runs the writer (mirroring the ``uv-lock`` hook): if the block
changes, the commit fails so the regenerated docs get staged. CI runs the same
hook via ``pre-commit run --all-files``, so a stale block turns the PR red.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# Pin the wrap width *before* importing argparse-built parsers: argparse reads
# COLUMNS via shutil.get_terminal_size, so this makes the output deterministic
# regardless of the terminal it runs in (local vs CI).
os.environ["COLUMNS"] = "80"

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_FILE = REPO_ROOT / "docs" / "usage" / "cli.md"

BEGIN = "<!-- BEGIN cli-help (auto-generated by scripts/gen_cli_docs.py — do not edit) -->"
END = "<!-- END cli-help -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)


def render_block() -> str:
    """Return the marker-wrapped, fenced ``--help`` output."""
    # Imported here so COLUMNS is already set when the parser/formatter is built.
    sys.path.insert(0, str(REPO_ROOT / "src"))
    from erdify.cli import build_parser

    help_text = build_parser().format_help().rstrip()
    return f"{BEGIN}\n\n```text\n{help_text}\n```\n\n{END}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the docs block is out of sync; do not write.",
    )
    args = ap.parse_args()

    current = DOCS_FILE.read_text(encoding="utf-8")
    if not BLOCK_RE.search(current):
        print(
            f"error: {DOCS_FILE.relative_to(REPO_ROOT)} has no cli-help markers "
            f"({BEGIN} ... {END})",
            file=sys.stderr,
        )
        return 2

    updated = BLOCK_RE.sub(lambda _m: render_block(), current)

    if updated == current:
        return 0

    rel = DOCS_FILE.relative_to(REPO_ROOT)
    if args.check:
        print(
            f"error: {rel} is out of sync with `erdify --help`.\n"
            "       Run `python scripts/gen_cli_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1

    DOCS_FILE.write_text(updated, encoding="utf-8")
    print(f"updated {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
